name: Build OCR Docker Image

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: self-hosted   # ใช้ self-hosted runner ของคุณ

    permissions:
      contents: read
      packages: write   # ✅ ต้องมีเพื่อ push ไป GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ocr-app:latest
            ghcr.io/${{ github.repository_owner }}/ocr-app:${{ github.sha }}

      - name: Smoke test imports (show which module fails)
        run: |
          set -eux
          docker run --rm ghcr.io/${{ github.repository_owner }}/ocr-app:latest \
            python - <<'PY'
import importlib, traceback
mods = ["flask","fastapi","uvicorn","sqlalchemy","paddle","paddleocr","tensorflow"]
for m in mods:
    print("== Test import:", m)
    try:
        mod = importlib.import_module(m)
        v = getattr(mod, "__version__", "n/a")
        print("OK:", m, v)
    except Exception:
        print("FAIL:", m)
        traceback.print_exc()
PY

      - name: Show pushed image info
        run: echo "Image pushed to ghcr.io/${{ github.repository_owner }}/ocr-app"
