name: Build OCR App Locally

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Buildx: โหลดเข้า local daemon ทันที (ห้ามใช้ร่วมกับ push: true)
      - name: Build (load to local Docker)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true             # ✅ สำคัญ
          tags: ocr-app:latest   # image จะโผล่ใน `docker images`

      # ตรวจสอบแบบไม่พึ่ง grep
      - name: Verify local image
        run: |
          docker image inspect ocr-app:latest >/dev/null
          docker images ocr-app:latest
