name: Build & Push OCR App

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

# ต้องมี เพื่อให้ GITHUB_TOKEN push เข้า GHCR ได้
permissions:
  contents: read
  packages: write

jobs:
  docker:
    # ใช้ได้กับทุก self-hosted runner (มีแค่ label self-hosted ก็พอ)
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/pongthesie/ocr-app:latest
            ghcr.io/pongthesie/ocr-app:${{ github.sha }}
