name: Build OCR App Locally

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Docker image locally
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false               # ❌ ไม่ push ขึ้น GHCR
          tags: ocr-app:latest      # tag local image

      # 4️⃣ Optional: Verify local Docker image
      - name: Verify Docker Image
        run: docker images | grep ocr-app
