name: Build & Push OCR App (Self-Hosted)

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login GHCR using PAT
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: pongthesie
          password: ${{ secrets.GHCR_PAT }}

      # 4️⃣ Build & Push Docker image (multi-platform optional)
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/pongthesie/ocr-app:latest
            ghcr.io/pongthesie/ocr-app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64  # comment ถ้าไม่ต้องการ multi-platform

      # 5️⃣ Optional: verify image
      - name: Verify Docker Image
        run: docker pull ghcr.io/pongthesie/ocr-app:latest
